### ISSUE TITLE
Feature Request: diagnostics message text object

### ISSUE THREAD

**Issue by Jeansidharta** [chrisgrieser/nvim-various-textobjs#10]
### Feature Requested

Hi

I think it'd be really useful to have a diagnostics message text object, to make it easier to google errors.

I'd be willing to submit a pull request with this feature, if you like.

Loving the project so far!

### Relevant Screenshot

![screenshot](https://user-images.githubusercontent.com/26410371/210133677-d40a1a47-faf1-4b90-9d03-d1c9c0131f63.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I like the idea (and would even use it myself), but I working with diagnostics in this way is outside the scope of this project, since that would not have anything to do with text objects anymore.

Nevertheless, you could write a snippet / mini-plugin for that I assume :)
