### ISSUE TITLE
Change Textobj: htmlAttribute

### ISSUE THREAD

**Issue by kola-web** [chrisgrieser/nvim-various-textobjs#102]
### Change requested

These are some of the property writings in jsx and vue that I have put together, please feel free to close them
support jsx onClick={activateLasers}
support vue slot v-slot:header & #header & v-slot:[dynamicSlotName] & #[dynamicSlotName]

### Sample Text

1. jsx 
<div onClick={activateLasers}></div>
2. vue template slot 
<template :name="name" #[dynamicSlotName] v-slot:[dynamicSlotName] #header v-slot:header></template>

### Checklist

- [X] The textobj would be useful to more users than just me. ([You can use the API to create custom textobj.](../#advanced-usage--api))
- [X] This is a feature request to change an existing textobject, not a bug report. (Use the bug report form for those.)

**Comment by chrisgrieser** [comment]
Sorry, vue and jsx adds too many edge cases for one text object to handle. 

For this, I'd suggest using mini.ai to create custom text objects.

**Comment by kola-web** [comment]
ok,thankyou
