### ISSUE TITLE
[Bug]: outer `lineCharacterwise` hangs the editor

### ISSUE THREAD

**Issue by TheSast** [chrisgrieser/nvim-various-textobjs#108]
### Bug Description

In visual mode using the outer version of `lineCharacterwise` while the cursor is on a `\n` character will hang the editor (CTRL-C does nothing).

### Reproduction & Sample Text

before: 
```
Lorem ipsum dolor sit amet
  visual mode cursor here ^ 
```
command (using default keymaps): `al`
after: it hangs
expected: it not hanging and selecting `Lorem ipsum dolor sit amet`

### neovim version

```Text
0.9.4
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Selections past the end of a line are definitely a weird thing, wasn't even aware that such a thing existed…

Not totally sure why this only occurs for this text object, but anyway, I added a workaround that fixes the issue.
