### ISSUE TITLE
[Bug]: entierBuffer object messes with user's `foldenable` setting

### ISSUE THREAD

**Issue by maciejzj** [chrisgrieser/nvim-various-textobjs#111]
### Bug Description

The `entireBuffer` object leaves the `foldenable` setting on, regardless of previous user settings. This causes `entireBuffer` operations like yanking (`ygG`) to fold my code as an unwanted side effect.

This is caused by the object code:

```lua
function M.entireBuffer()
	-- FIX folds at the first or last line cause lines being left out
	vim.opt_local.foldenable = false

	local lastLine = vim.api.nvim_buf_line_count(0)
	setLinewiseSelection(1, lastLine)

	vim.opt_local.foldenable = true -- <-- Always sets the option to true 
end
```

This problem can be easily mitigated by modyfying the function to:

```lua
function M.entireBuffer()
	-- FIX folds at the first or last line cause lines being left out
	local foldUserSetting = vim.opt_local.foldenable:get()
	vim.opt_local.foldenable = false

	local lastLine = vim.api.nvim_buf_line_count(0)
	setLinewiseSelection(1, lastLine)

	vim.opt_local.foldenable = foldUserSetting
end
```

I can open a PR with this change if you see it fit.

### Reproduction & Sample Text

Before:

In Command mode:

```
:set foldenable?
```

Prints: `nofoldenable`

In Normal mode:

```
ygG
```

After:

In Command mode:

```
:set foldenable?
```

Prints: `foldenable`

### neovim version

```Text
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
> I can open a PR with this change if you see it fit.

I was working on the repo already, so I just made the change myself. But generally, if you find an issue for which you have a straightforward and obvious fix like here, you don't need to ask for permission to make a PR, just create one. :) (Also, saves you the time to create a bug report.)
