### ISSUE TITLE
FR: when removing the first subword in a camelCased word, resulting word should be camelCased as well

### ISSUE THREAD

**Issue by chrisgrieser** [chrisgrieser/nvim-various-textobjs#113]
when removing the first subword in a camelCased word with `daS` I would expect the remaining word to still be camelCased. However, currently the word becomes PascalCased:

### Current behaviour (with cursor at `^`):

```
fooBarBaz
 ^
```

After pressing `daS`:

```
BarBaz
```

### Expected behaviour (with cursor at `^`):

```
fooBarBaz
 ^
```

After pressing `daS`:

```
barBaz
```

Note that would still expect `iS` to _not_ alter the case of the preceding word. That way if I wanted to just `c`hange the first subword, I could use `ciS` and get `BarBaz` (not `barBaz`).

This is also how [vim-textobj-variable-segment](https://github.com/Julian/vim-textobj-variable-segment) works. Do you also agree with this behaviour?

_Originally posted by @mawkler in https://github.com/chrisgrieser/nvim-various-textobjs/issues/83#issuecomment-2266629368_

**Comment by mawkler** [comment]
Works great! Thanks for implementing this!

**Comment by AlansCodeLog** [comment]
Hi, I've been having issues with deleting subwords where the word is PascalCase. The next word gets lowered cased (with cursor on pascal, `PascalCase` => `case` instead of `Case`) and I tracked it down to this commit. This is welcome for camelCase, but it seems to also be affecting PascalCase.

**Comment by chrisgrieser** [comment]
@AlansCodeLog Could you open a new bug report for that?

**Comment by chrisgrieser** [comment]
Nevermind, upon re-reading your comment, I understood what you mean. Fixed.

Nevertheless, next time, please report bugs in a new issue instead of using an old closed issue, since it makes things harder to track.
