### ISSUE TITLE
[Bug]: Smarter-gx broken on markdown link

### ISSUE THREAD

**Issue by qw457812** [chrisgrieser/nvim-various-textobjs#114]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.

### Bug Description

Thanks for great plugins (enjoy nvim-rip-substitute so much).

Smarter-gx is not working for markdown link recently. It grabs the trailing parentheses.

Edit: I have try new `smarter-gx` example from README.

### Reproduction & sample text

Press `gx` at start of this line:
[chrisgrieser/nvim-various-textobjs: Bundle of more than 30 new text objects for Neovim.](https://github.com/chrisgrieser/nvim-various-textobjs#smarter-gx).

Will open:
https://github.com/chrisgrieser/nvim-various-textobjs#smarter-gx).

Expected open:
https://github.com/chrisgrieser/nvim-various-textobjs#smarter-gx

### neovim version

```Text
NVIM v0.10.2
```

**Comment by chrisgrieser** [comment]
forgot to exclude `)` in the pattern, fixed.
