### ISSUE TITLE
[Bug]: `lineCharacterwise` hangs the editor when invoked on empty line

### ISSUE THREAD

**Issue by xeluxee** [chrisgrieser/nvim-various-textobjs#116]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.

### Bug Description

When `lineCharacterwise` textobject is invoked on an empty line the editor hangs.
After some inspection I've discovered that the following loop is causing the bug:

https://github.com/chrisgrieser/nvim-various-textobjs/blob/069f11ecabd18a170da96ad112498374dda57a31/lua/various-textobjs/textobjs/charwise/core.lua#L48-L53

Note that in such case `lineContent:find` returns `beginCol=1` and `endCol=0`.

May be related to #108.

### Reproduction & sample text

Put the cursor on an empty line, then use `lineCharacterwise` textobject.

### neovim version

```Text
v0.10.2
```

**Comment by xeluxee** [comment]
Thank you for the quick fix.

But I'm experiencing two other bugs with the latest commit (536bfa3956e591a1696482a6ca47e9f6ee81d774):
1. `lineCharacterwise` **inner** textobject includes trailing whitespaces when invoked on a line with trailing whitespaces
2. When `lineCharacterwise` textobject is invoked on an empy line a message is displayed: `Textobject not found within the line.`. While this looks correct, there are some use-cases where invoking such textobject on an empty line could be useful. An example is a macro to surround multiple consecutive lines with quotes: `qxysi_"j`. When this macro is called on an empty line I get the following result:

before
```
lorem ipsum

^ cursor above circumflex accent, on empty line
```

after pressing `ysi_"`
```
lorem ipsum"
"
```

expected result
```
lorem ipsum
""
```

**Comment by chrisgrieser** [comment]
> 1. lineCharacterwise inner textobject includes trailing whitespaces when invoked on a line with trailing whitespaces

ah, my bad, fixed.

> 2. When lineCharacterwise textobject is invoked on an empy line a message is displayed: Textobject not found within the line. 

Well, if you are on a blank line, there is no text object to match, really. if this was a linewise object, then it would just match the empty line, but with a characterwise text object, there is nothing left to match. The behavior is thus correct.

> While this looks correct, there are some use-cases where invoking such textobject on an empty line could be useful. An example is a macro to surround multiple consecutive lines with quotes: qxysi_"j

I am sorry to say, but I think "macro on empty line combined with surround plugin" is a bit too niche of a use case. Over the years as an open source maintainer, I've learned to avoid implementing things that complicate the code but only serve extremely niche cases. And I think this is one such case, sorry.

**Comment by xeluxee** [comment]
Thank you again for the quick fix.

> ah, my bad, fixed.

I'm still experiencing this issue with c975eeae80ed8ba3327e6dff6d6842d564f0dc64: put the cursor on a line with trailing whitespaces, press `vi_`, trailing spaces are selected.

> I am sorry to say, but I think "macro on empty line combined with surround plugin" is a bit too niche of a use case. Over the years as an open source maintainer, I've learned to avoid implementing things that complicate the code but only serve extremely niche cases. And I think this is one such case, sorry.

No problem, I'll find a solution myself.

**Comment by chrisgrieser** [comment]
> I'm still experiencing this issue

ah lol, I apparently only committed the comment, but not the actual fix itself. Maybe I accidentally pressed `u` before committing or something. Anyway, now the fix is commited.
![Pasted image 2024-12-14 at 02 26 29@2x](https://github.com/user-attachments/assets/90ad3f62-bd58-459d-98ad-b6086c904d69)

**Comment by xeluxee** [comment]
Now it works properly. Thanks.
