### ISSUE TITLE
Allow per-context usage of the indentation setting blanks_are_delimiters 

### ISSUE THREAD

**Issue by uwla** [chrisgrieser/nvim-various-textobjs#117]
### Checklist

- [X] The change would be useful to more users than just me. ([You can use the API to create custom text objects](../#advanced-usage--api).)
- [X] This is a feature request to change an existing text object, not a bug report. (Use the bug report form for those.)

### Change requested

I would like to know how to (or request change if not possible) have
`blanks_are_delimiter=true` for the text objects `ii` and `ai` and
at the same time to have `blanks_are_delimiter=false` for the text objects `iI` and `aI`

### Sample Text

For example:

```
 1. foo() {
 2.     item 1
 3.     item 2
 4.     item 3
 5. 
 6.     item 4
 7.     item 5 <-- cursor is here
 8.     item 6
 9. 
10.     item 7
11.     item 8
12.     item 9
13. }
```

* `ii` selects lines 7-9 (items 4-6)
* `ai` selects lines 5-9 (items 4-6 and lines above/below)
* `iI` selects lines 2-12 (items 1-9)
* `aI` selects lines 1-13 (items 1-9 and lines above/below)

**Comment by chrisgrieser** [comment]
Here is a solution for that: https://github.com/chrisgrieser/nvim-various-textobjs/issues/115#issuecomment-2529621129

**Comment by uwla** [comment]
This solution is buggy.

I tried the solution and selected text in visual mode using `ii`, `ai`, `iI`, `aI`, alternating a few times between, but `iI` and `aI` stops working after using it a few times.

**Comment by chrisgrieser** [comment]
> This solution is buggy.

In that case, please file a bug report with reproduction steps.
