### ISSUE TITLE
Feature Request: Current line textobj.

### ISSUE THREAD

**Issue by singlexyz** [chrisgrieser/nvim-various-textobjs#14]
### Feature Requested

Current line textobj request.

like https://github.com/kana/vim-textobj-line

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by singlexyz** [comment]
> I am not sure that I am getting it – isn't that already builtin? Like `dd`, `cc` and so on? Also there is the `_` which denotes the current line as a text object, e.g. `dd` being a synonym for `d_`

Shame for myself, I just found out about `_` motion today.

**Comment by chrisgrieser** [comment]
no worries, there is so much to learn about vim, you still learn something new after years of using it 😄

**Comment by 9mm** [comment]
This doesnt seem to work with `v`? how do I visually select the inner line, excluding whitespace, and including whitespace

**Comment by chrisgrieser** [comment]
@9mm If it does not work for you, it's most likely a different issue, so please open a bug report
