### ISSUE TITLE
[Bug]:  subword not working on capitalized text objects

### ISSUE THREAD

**Issue by juanpprieto** [chrisgrieser/nvim-various-textobjs#15]
### Bug Description

Thanks for this great plugin. 

After playing around with the various objects, I think I found this bug (or maybe it's the intended behavior)

```
type Test = {
  MY_KEY: string; 🚫 // diS replaces string instead of MY_
};

const obj = {
  MY_KEY: "test", 🚫 // diS replaces test instead of MY_
};

const my_var = "test"; ✅ replaces my_
```

### neovim version

```Text
0.9
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thanks, I simply forgot the case of screaming snake case. Fixed.
