### ISSUE TITLE
[Bug]: indentation object errors when at end of file

### ISSUE THREAD

**Issue by crides** [chrisgrieser/nvim-various-textobjs#16]
### Bug Description

when an indented line is at the end of a file, trying to select it will throw an "index out of bounds" error

### To Reproduce

1. paste the following into a buffer:
```
a
    b
```
2. place the cursor on the second line
3. `yii`

### neovim version

```Text
0.8.3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thanks, is fixed
