### ISSUE TITLE
xml attr

### ISSUE THREAD

**Issue by kola-web** [chrisgrieser/nvim-various-textobjs#18]
### Feature Requested

https://github.com/whatyouhide/vim-textobj-xmlattr

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Could you please describe how what exactly delimits such an xmlattr text object, since I am not familiar with XML?

**Comment by kola-web** [comment]
参考链接为 https://github.com/whatyouhide/vim-textobj-xmlattr

**Comment by chrisgrieser** [comment]
yes, I already saw the link the first time. However, as someone not familiar with XML, the link does not provide sufficient information for me to understand what an XML attribute is, I need some more information what counts as a xml attribute and what not

**Comment by chrisgrieser** [comment]
ah, those are just html attributes, I see. Added them just now, however, I implemented the difference between inner and outer slightly differently, `ax` targets the whole attribute, and `ix` only the value inside the quotes, hope that makes sense

**Comment by kola-web** [comment]
Thank you so I can fully migrate to this plugin
