### ISSUE TITLE
Feature Request: Include exhaustive mapping setup in the docs.

### ISSUE THREAD

**Issue by gerazov** [chrisgrieser/nvim-various-textobjs#19]
### Feature Requested

Great plugin! :sunglasses: 

It would be useful to include an exhaustive keymap setup in the README/docs so that users can cherry-pick the textobjects they wanna use and adjust any keymaps. Currently there are only a number of mappings given as examples, so it takes a more effort to customize before getting it up and running.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
good point, added 🙂
