### ISSUE TITLE
Feature Request: Consider de-deprecating key/value text objects

### ISSUE THREAD

**Issue by andrewferrier** [chrisgrieser/nvim-various-textobjs#20]
### Feature Requested

Would you consider de-deprecating the key and value text objects? I note in the readme you're referring to (I assume) the `assignment.lhs` and `assignment.rhs` text objs from https://github.com/nvim-treesitter/nvim-treesitter-textobjects. But I think they are actually less capable for two reasons:

* The treesitter-based ones *only* handle variable assignment - not assignment to fields inside objects, which `nvim-various-textobjs` does.

* The treesitter-based ones (at least currently) only support a fairly restricted set of languages, whereas this plugin uses pattern matching and so is a lot more flexible.

Longer-term, a more generalized text object based on treesitter might be really powerful, but I think we're a long way from that yet.

Just my 2c - I know the textobjs are still in the plugin right now, I'd just be disappointed to see them go.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
good point, I haven't thought of that. I always thought of the value textobj being inferior due to not being able to match multiline values. But your points make sense, I de-deprecated them until there are improvements with the treesitter textobjects.
