### ISSUE TITLE
[Bug]: gx-script prints stdout and stderr to buffer where the link was opened

### ISSUE THREAD

**Issue by astier** [chrisgrieser/nvim-various-textobjs#23]
### Bug Description

If I try to open a link with the gx-script on linux with firefox the stdout and stderr from firefox gets printed into the buffer right where the cursor is placed over the link. The link gets opened in firefox successfully though.

### Relevant Screenshot

![gx-bug](https://user-images.githubusercontent.com/36510152/225033383-0617f753-95a8-40dd-a6ea-3f866f4b980e.png)

### To Reproduce

1. Open nvim
2. Paste a link (ex. https://github.com/chrisgrieser/nvim-various-textobjs)
3. `gx` with cursor placed over link

### neovim version

```Text
0.8.3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by astier** [comment]
Redirecting it to `/dev/null` helps: `os.execute(opener .. " '" .. url .. "' > /dev/null 2>&1")`. Don't know if this would work on Windows.

**Comment by chrisgrieser** [comment]
Weird. Can't test since I am not on Linux. 

Nevertheless, since piping to dev-null cannot hurt, I just added that

**Comment by astier** [comment]
`>/dev/null 2>&1` is preferable to `&>/dev/null` because `&>/dev/null` is bashism (but I think also understood by zsh). Users may run another shell than bash which does not understand this syntax. I for example use bash only as my interactive shell but link /bin/sh to dash which is strictly POSIX-compliant (I think on Ubuntu /bin/sh is also linked by default to dash). With `&>/dev/null` some parts of stderr are still printed into my buffer after opening a link with `gx`. Using `>/dev/null 2>&1` fixes it.
