### ISSUE TITLE
Feature Request: line object

### ISSUE THREAD

**Issue by timbedard** [chrisgrieser/nvim-various-textobjs#24]
### Feature Requested

Could we add a line object similar to [vim-textobj-line](https://github.com/kana/vim-textobj-line)?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Nope – vim already has a line text object, so there is no need to add one: https://github.com/chrisgrieser/nvim-various-textobjs/issues/14#issuecomment-1451873159

**Comment by timbedard** [comment]
Huh. Yeah, I guess I can get `vil` for a line by doing `vim.keymap.set("x", "il", "^og_")`. Alrighty. Cheers.

**Comment by timbedard** [comment]
I do when operating on an entire line. I use `il` to operate on line contents _sans-whitespace_.

**Comment by chrisgrieser** [comment]
ah, so `dd` would delete the line, while `dil` would delete the line content, not changing the line number?

**Comment by chrisgrieser** [comment]
Added as `lineCharacterwise` textobj in the latest update 🙂

**Comment by timbedard** [comment]
Right. It leaves the newline and indentation. 👍
