### ISSUE TITLE
[Bug]: `toNextClosingBracket` is broken

### ISSUE THREAD

**Issue by amittamari** [chrisgrieser/nvim-various-textobjs#28]
### Bug Description

Looks like `toNextClosingBracket` is broken after this commit:
https://github.com/chrisgrieser/nvim-various-textobjs/commit/7cef84c275d191406e99e0aade866e77702df4c8

Tested in lazy using the [previous commit](https://github.com/chrisgrieser/nvim-various-textobjs/commit/b0ec67f8d06f03b5e84aa90eac96f6153100c963) SHA and it works as expected:
```
{
	'chrisgrieser/nvim-various-textobjs',
	commit = 'b0ec67f8d06f03b5e84aa90eac96f6153100c963',
}
```

### To Reproduce

1. Go to starting bracket
2. Go to next using `%`

Actual Result: Doesn't jump to next closing bracket

### neovim version

```Text
NVIM v0.10.0-dev-2647+g62b7b1daf-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Hmm, I cannot reproduce the issue, `d%` and other variants all work fine for me. Also, the commit you linked only changes a linting rule, so it cannot have broken anything.

Could you double check that the issue is not due to some conflicting keybinding or something on your end?

**Comment by amittamari** [comment]
Ahh, I see what I missed. It seems to break with lazy when passing in keymaps (to inform lazy when to lazy-load the plugin) in the plugin spec.

It breaks consistently for me in visual mode.

(what I meant in my original message was that the issue is non-existent on https://github.com/chrisgrieser/nvim-various-textobjs/commit/b0ec67f8d06f03b5e84aa90eac96f6153100c963 and is reproducible on https://github.com/chrisgrieser/nvim-various-textobjs/commit/7cef84c275d191406e99e0aade866e77702df4c8.)

Very weird, but managed to fix this by removing the `keys` and simply passed `lazy: true`.

**Comment by chrisgrieser** [comment]
> Very weird, but managed to fix this by removing the keys and simply passed lazy: true.

yep, when you add `lazy: true`, lazy will automatically load the plugin as soon as it is required by one of the keymaps. 🙂
