### ISSUE TITLE
[Bug]: iS/aS are incorrectly described

### ISSUE THREAD

**Issue by andrewferrier** [chrisgrieser/nvim-various-textobjs#3]
### Bug Description

iS/aS appear to work on sections of a word delimited by `_`, `-` or `.`. However, the docs say "never treating -, _ or . as word delimiters". What I think you mean is "*always* treating -, _ or . as word delimiters"?

### To Reproduce

In README.md

### neovim version

```Text
0.8.1
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
oh, you are right 😛 
thx, fixed
