### ISSUE TITLE
[Bug]: Unexpected behaviour when using `subword` on a number

### ISSUE THREAD

**Issue by musjj** [chrisgrieser/nvim-various-textobjs#32]
### Bug Description

When performing a `subword` operation on a number, unexpected behavior occurs. It either operates on a word on a different line or errors out with `Textobject not found within the next ... lines.`

I suppose that this object isn't _really_ intended for this, but I'm using it as a drop-in replacement for the native `iw`/`aw` object, so it would be nice if this use case can be covered.

### To Reproduce

1. Open any text file containing numbers
2. Move the cursor to the number
3. Perform an operation with the `subword` object

### neovim version

```Text
v0.10.0-dev-355+g3ae62c470
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
good point, I forgot to consider the case of just numbers / subword being used as a replacement for `iw`. Fixed

**Comment by musjj** [comment]
Thanks for the fast response, works great for me! :+1:
