### ISSUE TITLE
[Bug]: Incorrect indentation in `dsi`

### ISSUE THREAD

**Issue by adriafarres** [chrisgrieser/nvim-various-textobjs#37]
### Bug Description

Hello,

The following line in the `dsi` example in the README is incorrect:

```
vim.cmd.normal { ">" , bang = true }
```

It should be

```
vim.cmd.normal { "<" , bang = true }
```

### Reproduction & Sample Text

.

### neovim version

```Text
.
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thanks, fixed

**Comment by adriafarres** [comment]
Thank you. Your work on this plugin is very much appreciated :-)
