### ISSUE TITLE
New Textobj: Indentation Block

### ISSUE THREAD

**Issue by kevintraver** [chrisgrieser/nvim-various-textobjs#44]
### Textobj requested

From discussion: #43 

Here's an idea for a new text-object that might be useful: Indentation Block (open to ideas on other names this could be called)

Essentially, its the same as the indentation text object, but restricted by newlines.

example:

```
myFunction (abc)
  callMethod

  anotherMethod

  doSomething
  doSomethingElse  <-- cursor here
  doAnotherThing
end
```

would result in the following selection

```
  doSomething
  doSomethingElse
  doAnotherThing
```

### Inner/Outer Difference

Inner: does not contain any newlines
Outer: includes any bordering newlines (above and below)

### Filetypes

all

### Checklist

- [x] The textobj would be useful to more users than just me.
- [X] There is no lua plugin already implementing the textobj in an adequate manner.
- [X] I read the docs and there is no such textobj already.

**Comment by bew** [comment]
There is a vimscript implementation of this behavior: https://github.com/kana/vim-textobj-indent , under `ii` omap. (`ai` omap of this plugin is the whole content of the function, everything with same indentation as current line)

**Comment by kevintraver** [comment]
Yeah. I wonder how hard that is to move to lua. It looks like most of the the logic is already done with the *indentation* text object in this plugin.

**Comment by chrisgrieser** [comment]
implemented via #54

**Comment by kevintraver** [comment]
> implemented via #54

Works great!

One other thing feature that might be nice:

When selecting the indentation block and restricting by new lines (using `noBlanks`) it would be nice if this worked even when there is no indentation. It would basically just select up and down until empty lines.

Obviously the `withBlanks` does not make sense with no indentation because it would just be the entire buffer.

**Comment by chrisgrieser** [comment]
>  It would basically just select up and down until empty lines.

but isn't that what you would get with the `ip` textobject already?

**Comment by kevintraver** [comment]
Sort of. When there is no indentation it is effectively the same thing.

But then `ap`/`ip` does not work when there is indentation. Which is where this new text object comes in.

My goal is to have the same text object work when selecting for both indentation and no indentation (stopping on newlines)

No indentation:
```
myFunction (abc)
  someMoreStuff
end

someMoreText
someMoreText       <-- cursor here
someMoreText

anotherFunction (abc)
  helloWorld
end
```
selects:
```
someMoreText
someMoreText
someMoreText
```

With Indentation
```
myFunction (abc)
  callMethod

  doSomething
  doSomethingElse
  doAnotherThing    <--- cursor here

  anotherMethod
end
```
selects:
```
  doSomething
  doSomethingElse
  doAnotherThing
```

**Comment by kevintraver** [comment]
Here is where `ip`/`ap` does not work:
```
myFunction (abc)
  callMethod

  doSomething
  doSomethingElse
  doAnotherThing

  anotherMethod       <-- cursor here
end
```
`v` `ip` ends up selecting:
```
  anotherMethod
end
```

**Comment by chrisgrieser** [comment]
That's what by I use the greedyOuterIndentation textobj for

**Comment by kevintraver** [comment]
Here is another example of how this would work:

```
myFunction()
  anotherMethod

  someMethod              <-- cursor here
end

anotherFunction()
  anotherMethod
end
someOtherFunction()

moreFunctions()
```
would select:
```
  someMethod
```
and then:
```
myFunction()
  anotherMethod

  someMethod
end

anotherFunction()         <-- cursor here
  anotherMethod
end
someOtherFunction()

moreFunctions()
```
would select:
```
anotherFunction()
  anotherMethod
end
someOtherFunction()
```

The goal is to have both scenarios work with the same text object.

**Comment by chrisgrieser** [comment]
Tbh, I personally would find such behavior unintuitive. And I also hesitate a bit to support too many niche cases; I've had projects that became a bit overburdened by considering too many niche use cases. 

Nevertheless, the beauty of a customizable editor like nvim is that you can easily create a textobj of your own with a ~four line function that switches between ip and ii depending on the current indentation level (`vim.fn.indent(".")`). :)

**Comment by kevintraver** [comment]
Thanks for that suggestion! I will try that. I think it should work for what I am trying to achieve.
