### ISSUE TITLE
[Bug]: `av` textobject assumes there's a space before `=`

### ISSUE THREAD

**Issue by ces42** [chrisgrieser/nvim-various-textobjs#47]
### Bug Description

`av` includes the charater to the

### Reproduction & Sample Text

before: `key=value`
then do `daw`
after: `ke`
expected: `key`

### neovim version

```Text
v0.10.0-dev-858+gd25e45d2a
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Thanks, issue has been fixed.
