### ISSUE TITLE
Feature Request: 'Key'/LHS

### ISSUE THREAD

**Issue by andrewferrier** [chrisgrieser/nvim-various-textobjs#5]
### Feature Requested

`iv` and `av` are really interesting text objects I've not seen elsewhere. I'd really love to see support for the left-hand-side of an expression / key in a object.

Thanks for all your great work on this plugin so far!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
ah good idea, why didn't I think of that. Added 🙂

**Comment by andrewferrier** [comment]
Nice! Thank you.
