### ISSUE TITLE
Textobj change: entire buffer

### ISSUE THREAD

**Issue by Nekketsu** [chrisgrieser/nvim-various-textobjs#50]
### Textobj requested

It exists this plugin:
[vim-textobj-entire](https://github.com/kana/vim-textobj-entire)

In [nvim-various-textobjs](https://github.com/chrisgrieser/nvim-various-textobjs) there is something similar, `entireBuffer`, `gG`. However, with [vim-textobj-entire](https://github.com/kana/vim-textobj-entire) there is a `textobject` for the entire buffer, and a `textobject` for the entire buffer `ae` but without the leading and trailing empty lines `ie`.

Would it be possible to have something similar in [nvim-various-textobjs](https://github.com/chrisgrieser/nvim-various-textobjs)?

### Inner/Outer Difference

- **outer**: Entire Buffer.
- **inner**: Entire Buffer without leading or trailing empty lines.

### Vimscript plugin already implementing the textobj

[vim-textobj-entire](https://github.com/kana/vim-textobj-entire)

### Filetypes

all

### Checklist

- [X] The textobj would be useful to more users than just me.
- [X] There is no lua plugin already implementing the textobj in an adequate manner.
- [X] I read the docs and there is no such textobj already.

**Comment by chrisgrieser** [comment]
Tbh, I find that a bit too much of a niche case and I hesitate supporting too many niche use cases. Usually a modern formatter will already trim whitespace at the beginning and end of the file. 

That being said, if you really want that feature, with nvim being a very customizable editor, you could create a text object of your own that does what you want with about 4 lines of code, see the advanced usage examples in the readme on how to create small functions using text objects of this plugin.
