### ISSUE TITLE
[Bug]: Overrides visual mode r

### ISSUE THREAD

**Issue by YodaEmbedding** [chrisgrieser/nvim-various-textobjs#52]
### Bug Description

Rest of paragraph overrides the default vim behavior of `r` in visual mode.

Partial workaround: using `c`...`<Esc>` instead of `r` in visual mode covers 80% of use cases for `r`.

### Reproduction & Sample Text

```vim
:vnoremap r

x  r           * <Cmd>lua require('various-textobjs').restOfParagraph()<CR>
                 restOfParagraph textob
```

### neovim version

```Text
0.9
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
tbh, I am inclined to keep it, since I think that a lot of people do not actually ever use `r` in visual mode. And in the rare case that they do, they can just disable the keymap?
