### ISSUE TITLE
New Textobj: item in list ","

### ISSUE THREAD

**Issue by gerazov** [chrisgrieser/nvim-various-textobjs#58]
### Textobj requested

Select item in a list of items separated with `,` and bound by brackets or newlines, e.g:

```python
a = [1, 2, 3, 4]
b = [
    1, 2, 3, 4
    ]
```

This is similar to argument, but argument is limited to `()`.

### Inner/Outer Difference

Inner leaves the `,`
Outer includes the preceding (following if first item) `,`

### Filetypes

all

### Checklist

- [X] The textobj would be useful to more users than just me.
- [X] There is no lua plugin already implementing the textobj in an adequate manner.
- [X] I read the docs and there is no such textobj already.

**Comment by chrisgrieser** [comment]
You can use the argument textobj from [treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) for that already :)

**Comment by gerazov** [comment]
Well not really, or at least as much as I know - the argument object works only for arguments in a function call, i.e. it'll work only if the items are bounded by `( )` and not in the case above.

**Comment by chrisgrieser** [comment]
as I said, is many languages like in lua, it also works for array elements. If it does not work in your language, it'd therefore make more sense to make a FR there instead of re-implementing the same textobj again here

**Comment by gerazov** [comment]
Oh you're right - it does work :sweat_smile: my bad - I thought I tested it  ...

**Comment by gerazov** [comment]
It would be useful for pure text, e.g.
```txt
This is a list of items in: rst, md, txt, text, mail files. 
```
Here the treesitter solution doesn't work. Also for comments in code scripts that list stuff.

**Comment by chrisgrieser** [comment]
Like a sub-sentence? Hmm. I can see a lot of potential edge cases for this (where does the first element in the list start, what about decimal commas and thousand separators, etc.)

Could you open a new issue for it since it's somewhat different, and also detail how exactly such a text object should behave?
