### ISSUE TITLE
[Bug]: iS and aS off by one

### ISSUE THREAD

**Issue by n0bra1n3r** [chrisgrieser/nvim-various-textobjs#59]
### Bug Description

When I do `diS` or `daS` with the default config, the entire subword except for the last character is deleted.

### Reproduction & Sample Text

before: subWord
after: bWord
expected: Word

### neovim version

```Text
0.9.4
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
sorry, I cannot reproduce your example. Maybe you have some other plugin interfering?
