### ISSUE TITLE
[Bug]: 'diagnostic' text object does not work when sitting on the diagnostic

### ISSUE THREAD

**Issue by andrewferrier** [chrisgrieser/nvim-various-textobjs#6]
### Bug Description

'diagnostic' text object does not work when sitting *on* the diagnostic

This I think is because you are using `vim.diagnostic.next`, which is useful for searching but not for locating items you may be sitting on. This is one of the reasons I wrote more sophisticated search logic in `vim-textobj-diagnostic`: https://github.com/andrewferrier/textobj-diagnostic.nvim/blob/1b36edbb83c0d179621015b9cb35ebd487cb78dc/lua/textobj-diagnostic.lua#L47. Feel free to use/adapt that if you wish.

### To Reproduce

1. Create a buffer with a diagnostic more than one character wide.
2. Sit 'on' the diagnostic (move the cursor to half-way along it).
3. Type 'y!' or similar (whatever key has been assigned). Note that nothing is yanked.
4. Move elsewhere in the buffer and repeat. Note that now the value is yanked.

### neovim version

```Text
0.8.1
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
and here I thought [this nice short solution would suffice](https://github.com/chrisgrieser/nvim-various-textobjs/blob/main/lua/various-textobjs.lua#L232-L241) 🙈

I'll look into your code later on, but since you are familiar with the issue already anyway, feel free to make a PR?

**Comment by andrewferrier** [comment]
Sure - I'll take a look when I have some time. Might be a few days though...

**Comment by chrisgrieser** [comment]
fixed. And thanks to an idea @Jeansidharta gave me in #9, it didn't even require going through all diagnostics: if the cursor is standing on a diagnostic, `diagnostic.get_prev()` will return it, which made the implementation quite a bit easier. 🙂

**Comment by andrewferrier** [comment]
Thanks @chrisgrieser, this seems to work well. For you information, I have now semi-deprecated my own https://github.com/andrewferrier/textobj-diagnostic.nvim and have redirected folks over here to your plugin. I may in future deprecate or archive my plugin.
