### ISSUE TITLE
New Textobj: item in list seperated with "," or similar

### ISSUE THREAD

**Issue by gerazov** [chrisgrieser/nvim-various-textobjs#60]
### Textobj requested

Select item in a list of items separated with `,` . Although treesitter parsers already do this for code (#58) via the in argument mechanic [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/), it would be useful to have it for lists in pure text, e.g.
```txt
This is a list of items in: rst, md, txt, text, mail files. 
```
Also could come in handy for comments in code scripts that list stuff.

The syntax would be `i<separator>` for inner and `a<separator>` for outer. Here `<separator>` can be `,`, `;`, ...

### Inner/Outer Difference

In it's simplest use-case - inner `i,` would not take the separator, and around `a,` would e.g. if your cursor is on `text` then:
```txt
This is a list of items in: rst, md, txt, text, mail files. 
                                          |--| inner
                                outer   |----|
```

Edge cases would be the **first element**:
- the right bound is the `,`
- the left bound:
    - if there is a `:` or `-` starting the list than it is taken as a bound of the first item,
    - if not then the first item could be a single word.

And for the **last element**:
- the right bound is the `.`
- the left bound:
    - the `and` if there is one
    - the previous `,`

### Vimscript plugin already implementing the textobj

https://github.com/wellle/targets.vim

### Filetypes

all

### Checklist

- [X] The textobj would be useful to more users than just me.
- [X] There is no lua plugin already implementing the textobj in an adequate manner.
- [X] I read the docs and there is no such textobj already.

**Comment by bew** [comment]
Bump 🙏
