### ISSUE TITLE
[Bug]: htmlAttribute` does not work with single quotes

### ISSUE THREAD

**Issue by thenbe** [chrisgrieser/nvim-various-textobjs#62]
### Bug Description

The `htmlAttribute` text object does not work with single quotes. It works fine with double qoutes.

### Reproduction & Sample Text

In this example, the `htmlAttribute` is only detected on the first line. It is not detected on the second line.

```html
<div class="flex mt-6 bg-red-500"></div>
<div class='flex mt-6 bg-red-500'></div>
```

### neovim version

```Text
NVIM v0.10.0-dev-7ca2d64
Build type: Release
LuaJIT 2.1.1693350652
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thanks, fixed
