### ISSUE TITLE
Implement dot-repeatability

### ISSUE THREAD

**Issue by lbiaggi** [chrisgrieser/nvim-various-textobjs#7]
### Feature Requested

I think you could use something like my snippet, although it depends on `vim-repeat`. It's worth to use or at least suggest this way to bind.

```lua
vim.keymap.set("n", "]d", function() vim.diagnostic.goto_next { float = false } vim.call("repeat#set", "]d") end,
    { noremap = true })
vim.keymap.set("n", "[d", function() vim.diagnostic.goto_prev { float = false } vim.call("repeat#set", "[d") end,
    { noremap = true })
vim.keymap.set("n", "]D",
    function() vim.diagnostic.goto_next { severity = vim.diagnostic.severity.ERROR, float = false }
        vim.call("repeat#set"
            , "]D")
    end, { noremap = true })
vim.keymap.set("n", "[D",
    function() vim.diagnostic.goto_prev { severity = vim.diagnostic.severity.ERROR, float = false }
        vim.call("repeat#set"
            , "[D")
    end, { noremap = true })
```

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
thanks! I refrain from adding vim-repeat as dependency though, since I prefer to implement dot repeatability down the line without it. But I'll happily link to this info until then

**Comment by milanglacier** [comment]
https://www.vikasraj.dev/blog/vim-dot-repeat

This is a reference: you don't need vim-repeat to make it repeatable

**Comment by chrisgrieser** [comment]
Thanks! I'll look into it

**Comment by lbiaggi** [comment]
maybe: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/343/files#diff-d556bde8482509ad3531865672ab1bf4eb8b4d2e2224fdbd5d61fcfc86183326R6-R14 ?

**Comment by chrisgrieser** [comment]
Okay, so I looked into the linked guide as well as [another guide I found](https://gist.github.com/kylechui/a5c1258cd2d86755f97b10fc921315c3) and I am able to get simple examples with dot-repeatability going.

However, both guides as well as the example from op implement dot-repeatability for *normal-mode*, whereas for this plugin, I'd need to add dot repeatability to an mapping for *operating-pending-mode*, for which dot repeatability apparently has to be implemented differently (the objects needs to be fully called again, not the operator, which is already dot-repeatable).

Does someone here know any guides or plugins that explain how to make text objects dot-repeatable?

**Comment by lbiaggi** [comment]
I was thinking maybe https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/incremental_selection.lua can help.

**Comment by andrewferrier** [comment]
> Okay, so I looked into the linked guide as well as [another guide I found](https://gist.github.com/kylechui/a5c1258cd2d86755f97b10fc921315c3) and I am able to get simple examples with dot-repeatability going.
> 
> However, both guides as well as the example from op implement dot-repeatability for _normal-mode_, whereas for this plugin, I'd need to add dot repeatability to an mapping for _operating-pending-mode_, for which dot repeatability apparently has to be implemented differently (the objects needs to be fully called again, not the operator, which is already dot-repeatable).
> 
> Does someone here know any guides or plugins that explain how to make text objects dot-repeatable?

@chrisgrieser it's not a guide per se, but you might find the implementation of dot-repeat in my `debugprint.nvim` plugin helpful: https://github.com/andrewferrier/debugprint.nvim: https://github.com/andrewferrier/debugprint.nvim/blob/ee5a3a83c87e6a50dcb1223212404240ca519bdd/lua/debugprint/init.lua#L346.

The challenge I think is that you have to decide whether dot-repeating repeats with the same *value* of the text object, or the same text object. For example, in my case, dot-repeating prints another debug line, with the value of the original text object from the first line printed (this is hard to explain, but try it). But you could presumably implement this such that it selects the text object again given the new cursor position.

I don't know if there's a standard approach there.

**Comment by chrisgrieser** [comment]
Thanks to the [a great find](https://github.com/chrisgrieser/nvim-spider/pull/4) by @vypxl and @ii14, the plugin now supports dot-repeatability. 🥳 

While this is a non-breaking change, you do need to change your keymaps. See the README. 🙂
