### ISSUE TITLE
FR: `multiCommentedLines()` doesn't select single-line comments

### ISSUE THREAD

**Issue by savchenko** [chrisgrieser/nvim-various-textobjs#74]
### Bug Description

This selects multi-line comments (as the name implies), but fails to pick-up single lines.

```lua
lua require('various-textobjs').multiCommentedLines()
```

Perhaps would make sense to allow it, even if via an optional parameter?

### Reproduction & Sample Text

`[*]` denotes cursor position:

```lua
[*]

            { -- Various non-TS objects
                url = 'https://github.com/chrisgrieser/nvim-various-textobjs',
                config = function ()
                    require("various-textobjs").setup({ useDefaultKeymaps = false })
```

### neovim version

```Text
v0.9.4
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
This is actually deliberate, since treesitter-textobjects already allows you to target single line comments. So I use treesitter textobjects for single line comments, and various textobjs for multi-line comments

**Comment by chrisgrieser** [comment]
No. But you should be able to build one yourself, if you disable forward-looking, similar to one of these examples:
https://github.com/chrisgrieser/nvim-various-textobjs?tab=readme-ov-file#advanced-usage--api
