### ISSUE TITLE
[Bug]: Subword jumps / doesn't select single character subwords.

### ISSUE THREAD

**Issue by AlansCodeLog** [chrisgrieser/nvim-various-textobjs#75]
### Bug Description

Not sure if this might be intended, but for example if my cursor `|` is on a word like `|xSide` , if I do a subword selection it selects `Side`, but if I'm on `sideX|`, I get `X`. Using camelcase I would expect `x` to also be a subword here and not jump ahead. 

I see some commands are forward seeking but as far as I understood the table subword shouldn't be, but I'm getting jumping in cases like `| xSide` => `Side` as well.

I know it sounds maybe a bit odd to want a single character subword but reason I ran into this is I'm making a word cycling plugin and using this plugin to get the subword. And I'd like to be able to make single character replacements (e.g. x for y). I can work around this I think, but would be nice to just use subword directly. 

### Reproduction & Sample Text

before: `|xSide` after: `x|Side|` expect: `|x|Side`
before: `| xSide` after: ` x|Side|` expect: ` |x|Side`

### neovim version

```Text
v0.9.5

Plugin version is 035243e
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by tuurep** [comment]
bad bot

**Comment by chrisgrieser** [comment]
Sorry, I've been putting off this one for a while, since I was afraid that this would have tons of edge cases to consider. But to my surprise, this was actually a quite simple one-line fix, since the algorithm I wrote back then already considered all the edge cases I could think of right now 😅
