### ISSUE TITLE
Change Textobj: `multiCommentedLines()` Outer version

### ISSUE THREAD

**Issue by Nekketsu** [chrisgrieser/nvim-various-textobjs#77]
### Change requested

I would like to have an `outer` version of the `multiCommentedLines()`.
For me the inner version is the current one, and the outer should be a new one:
- inner: current behavior
- outer: pick also blank lines (empty or whitespaces)

### Sample Text

Having the following code, and having the cursor in the first line `// Comment 1`:
```
// Comment 1
// Comment 2

// Comment 3
// Comment 4
```

The inner version should keep the current behavior: it will select the following lines:
```
// Comment 1
// Comment 2
```
The outer version should select all the lines, including empty blank lines:
```
// Comment 1
// Comment 2

// Comment 3
// Comment 4
```

### Checklist

- [X] The textobj would be useful to more users than just me. ([You can use the API to create custom textobj.](../../README.md#advanced-usage--api))
- [X] This is a feature request to change an existing textobject, not a bug report. (Use the bug report form for those.)

**Comment by chrisgrieser** [comment]
`multiCommentedLines` has been removed since it has been implemented in nvim core as of 0.10: https://neovim.io/doc/user/various.html#o_gc

This thus also makes this issue obsolete, I'd suggest opening a FR at nvim for that now, sorry.
