### ISSUE TITLE
[Bug]: indentation object errors when at end of file

### ISSUE THREAD

**Issue by adriafarres** [chrisgrieser/nvim-various-textobjs#79]
### Bug Description

This is analogous to #16, but for operator `restOfIndentation`.

### Reproduction & Sample Text

1. paste the following into a buffer:
```
a
    b
```

2. place the cursor on the second line
3. `:lua require('various-textobjs').restOfIndentation(false, true)`

### neovim version

```Text
NVIM v0.10.0-dev-2537+g6d680d9775
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
fixed 👍

**Comment by adriafarres** [comment]
Thank you! :-)
