### ISSUE TITLE
New Textobj: LSP `textDocument/documentLink`

### ISSUE THREAD

**Issue by pbnj** [chrisgrieser/nvim-various-textobjs#80]
### Textobj requested

Similar to the LSP diagnostic support provided by `nvim-various-textobjs`, it would be nice if LSP `textDocument/documentLink` is supported by this plugin as well.

#### Terraform

```terraform
provider "aws" {} // launch terraform provider docs
```

#### Go

```go
package main

import "fmt" // launch go pkg docs

func main() {
    fmt.Println("hello world")
}
```

#### Rust

```rust
/// See [`foo`](foo)
/// See [`std::fs::read()`]
fn main() {}
```

### Vimscript plugin already implementing the textobj

Not vimscript, but https://github.com/icholy/lsplinks.nvim provides this functionality. If it is possible to integrate the two plugins so that `gx` plays nicely with both plugins, that would be an acceptable solution.

### Filetypes

all

### Checklist

- [X] The textobj would be useful to more users than just me. ([You can use the API to create custom textobj.](../../README.md#advanced-usage--api))
- [X] There is no lua plugin already implementing the textobj in an adequate manner.
- [X] I read the docs and checked that there is no such textobj already.

**Comment by chrisgrieser** [comment]
Hmm, I think providing a text object like that would be the job of lsplinks, since it would require usage of that lsp interface, and doing so in various textobj would most likely result duplicate work. 

Thus I think this request should rather be made at the lsplinks repo

**Comment by pbnj** [comment]
That's reasonable.

Since both plugins use `gx`, is there a way to make a ["smarterer `gx`"](https://github.com/chrisgrieser/nvim-various-textobjs?tab=readme-ov-file#smarter-gx) such that it would do the right thing for lsplinks and url textobjs?

**Comment by chrisgrieser** [comment]
Well, you could for example prioritize regular URLs, and if no regular URL has been found[^1], call the lsplinks `gx command`. Basically, in the linked snippet, insert the lsplinks command into an `else` block, instead of the `if not foundURL then return end`.

[^1]: in the next few lines, number depending on config
