### ISSUE TITLE
[Question]: How do I get the old behaviour for multiline comments?

### ISSUE THREAD

**Issue by sahinakkaya** [chrisgrieser/nvim-various-textobjs#84]
### Bug Description

82b43339078414f3a26b033486257b80a647991f removes `gc` text object saying it is default in nvim 0.10. I checked the `:h news` and didn't understand how I can make use of this default feature. Maybe someone can help?

### Reproduction & Sample Text

.

### neovim version

```Text
0.10.0
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
From nvim 0.10 on, there is a `gc` textobject which pretty much does what `multiCommentedLines` did: https://neovim.io/doc/user/various.html#o_gc

So if you used `gc` as mapping, it will work out of the box, if you used a different mapping, you have to remap it to `gc`.

**Comment by sahinakkaya** [comment]
Oh, it only works in operator pending mode. I was trying to select the multicommented lines with `vgc` and it wasn't working. Thanks for pointing to the documentation.

**Comment by chrisgrieser** [comment]
FYI for anyone looking for the using multiline comments in visual mode, see this comment: https://github.com/chrisgrieser/nvim-various-textobjs/issues/93#issuecomment-2255437246
