### ISSUE TITLE
New [Old] Textobj: multiCommentedLines

### ISSUE THREAD

**Issue by carschandler** [chrisgrieser/nvim-various-textobjs#93]
### Textobj requested

It seems that the multiCommentedLines object was removed in favor of the new native `gc` object. However, there is no way to visually select this object in native neovim, but this was possible via this plugin. Maybe consider bringing it back since I doubt they will bring this into native neovim?

treesitter's implementation is really bad because it selects text leading up to the line following the text object and can't grab entire multi-line comments

### Sample Text

As implemented previously

### Filetypes

As implemented previously

### Checklist

- [X] The textobj would be useful to more users than just me. ([You can use the API to create custom textobj.](../../README.md#advanced-usage--api))
- [X] There is no lua plugin already implementing the textobj in an adequate manner.
- [X] I read the docs and checked that there is no such textobj already.

**Comment by chrisgrieser** [comment]
I do not like the idea of adding a text object *solely* for visual mode, as in my view, the primary use case for text objects is in my view operator-pending mode. 

Here is the old code for creating the `multiCommentedLines` function, which you can use to create the keymap, if you want to.

```lua
local M = {}

local function isVisualLineMode()
	local modeWithV = vim.fn.mode():find("V")
	return modeWithV ~= nil
end
local function normal(cmd) vim.cmd.normal { cmd, bang = true } end
local function isCommentedLine(lnum)
	local commentStringRegex = "^%s*"
		.. vim.pesc(vim.bo.commentstring):gsub(" ?%%%%s ?", ".*")
		.. "%s*$"
	return vim.fn.getline(lnum):find(commentStringRegex) ~= nil
end
local function setLinewiseSelection(startline, endline)
	vim.api.nvim_win_set_cursor(0, { startline, 0 })
	if not isVisualLineMode() then normal("V") end
	normal("o")
	vim.api.nvim_win_set_cursor(0, { endline, 0 })
end

---@param lookForwL integer number of lines to look forward for the textobj
function M.multiCommentedLines(lookForwL)
	if vim.bo.commentstring == "" then
		vim.notify("Buffer has no commentstring set.")
		return
	end

	local curLnum = vim.api.nvim_win_get_cursor(0)[1]
	local startLnum = curLnum
	local lastLine = vim.api.nvim_buf_line_count(0)

	while not isCommentedLine(curLnum) do -- when on blank line, use next line
		if curLnum == lastLine or curLnum > startLnum + lookForwL then
			vim.notify("No commented line found.")
			return
		end
		curLnum = curLnum + 1
	end

	local prevLnum = curLnum
	local nextLnum = curLnum
	while prevLnum > 0 and isCommentedLine(prevLnum) do
		prevLnum = prevLnum - 1
	end
	while nextLnum <= lastLine and isCommentedLine(nextLnum) do
		nextLnum = nextLnum + 1
	end

	setLinewiseSelection(prevLnum + 1, nextLnum - 1)
end

return M
```
