### ISSUE TITLE
Change Textobj: lineCharacterwise and entireBuffer to maintain cursor positions

### ISSUE THREAD

**Issue by mangelozzi** [chrisgrieser/nvim-various-textobjs#94]
### Change requested

I tried this plug in with:
```
-- Own map preserves the cursor position
-- vim.keymap.set({ "o", "x" }, "al", '<cmd>lua require("various-textobjs").lineCharacterwise("outer")<CR>')
-- vim.keymap.set({ "o", "x" }, "il", '<cmd>lua require("various-textobjs").lineCharacterwise("inner")<CR>')

-- Own way prefers the position of the cursor on copy all
-- vim.keymap.set({ "o", "x" }, "A", '<cmd>lua require("various-textobjs").entireBuffer()<CR>')
```

But reverted to my own keymaps because they maintain the cursor position on copy the entire buffer or copy a line. I find it much less jarring, maybe others will benefit from this upgraded behavior?

```
vim.keymap.set({"x", "o"}, "il", ":<C-U>normal! ^vg_<CR>", {noremap = true})
vim.keymap.set({"x", "o"}, "al", ":<C-U>normal! 0vg_<CR>", {noremap = true})

-- utils.lua
-- Text object to select the whole buffer, used in normal/visual modes
function M.text_object_all()
    vim.g.cursor_position = vim.fn.winsaveview()
    vim.cmd("normal! ggVG")
    local pattern = "[cd]" -- 'c' or 'd'
    if not string.find(vim.v.operator, pattern) then
        -- Running the command straight does not work, have to pass it through feedkeys or defer it
        vim.defer_fn(
            function()
                vim.fn.winrestview(vim.g.cursor_position)
            end,
            0
        )
    end
end

-- Some other file
vim.keymap.set("o", "A", utils.text_object_all, {})
```

### Sample Text

No change, just maintain the cursor position when copying a line or the entire buffer

### Checklist

- [X] The textobj would be useful to more users than just me. ([You can use the API to create custom textobj.](../#advanced-usage--api))
- [X] This is a feature request to change an existing textobject, not a bug report. (Use the bug report form for those.)

**Comment by chrisgrieser** [comment]
I think it makes more sense to have the stickiness (= keeping the cursor position) be something managed by the operator, not by the text object. That way, it works independent of any text object.

You can achieve sticky yank operations either by using the [yanky.nvim](http://github.com/gbprod/yanky.nvim), or by using these. They work reliably with any text object, be it this plugin, a different plugin, or the builtin vim motions.

```lua
local cursorPreYank
vim.keymap.set({ "n", "x" }, "y", function()
	cursorPreYank = vim.api.nvim_win_get_cursor(0)
	return "y"
end, { desc = "Sticky Yank", expr = true })
vim.keymap.set("n", "Y", function()
	cursorPreYank = vim.api.nvim_win_get_cursor(0)
	return "y$"
end, { desc = "Sticky Yank", expr = true })

vim.api.nvim_create_autocmd("TextYankPost", {
	callback = function()
		if vim.v.event.operator == "y" and cursorPreYank then
			vim.api.nvim_win_set_cursor(0, cursorPreYank)
		end
	end,
})
```
