### ISSUE TITLE
Change Textobj: Consider extending `{notifyNotFound=false}` to indentation object's warning "Current line is not indented"

### ISSUE THREAD

**Issue by tuurep** [chrisgrieser/nvim-various-textobjs#97]
### Change requested

I'd prefer to have all warnings turned off when there's nothing to be done, so would feel consistent if for example `dii` on an unindented line wouldn't give a warning message either when `notifyNotFound=false`

Looks like there's also a warning "No indented line found." [(code)](https://github.com/chrisgrieser/nvim-various-textobjs/blob/b8f7e971672aea04b754b70feb53b0bc71901a7c/lua/various-textobjs/linewise-textobjs.lua#L173-L177) associated with indentation textobj, but I haven't found in what situation that emits. But most likely my request concerns that too.

Relevant PR where `notifyNotFound` was added: https://github.com/chrisgrieser/nvim-various-textobjs/pull/85

### Sample Text

```lua
require("various-textobjs").setup({notifyNotFound = false})
```

```
Unindented line hello foo bar
^
```

Press `dii`

Gives warning `"Current line is not indented."`

But could it be quiet?

### Checklist

- [X] The textobj would be useful to more users than just me. ([You can use the API to create custom textobj.](../#advanced-usage--api))
- [X] This is a feature request to change an existing textobject, not a bug report. (Use the bug report form for those.)

**Comment by tuurep** [comment]
It could be opinionated though because this isn't the same kind of "not found **within n lines**" message as the one disabled by `notifyNotFound=false`.

Alternative idea: some kinda `quiet` option, as a sort of second level of quietness.

**Comment by tuurep** [comment]
Thanks, yeah I can make one and good to know my request made perfect sense :)

**Comment by tuurep** [comment]
Although are there more cases related to this? Examples:

https://github.com/chrisgrieser/nvim-various-textobjs/blob/b8f7e971672aea04b754b70feb53b0bc71901a7c/lua/various-textobjs/charwise-textobjs.lua#L265
https://github.com/chrisgrieser/nvim-various-textobjs/blob/b8f7e971672aea04b754b70feb53b0bc71901a7c/lua/various-textobjs/charwise-textobjs.lua#L417
https://github.com/chrisgrieser/nvim-various-textobjs/blob/b8f7e971672aea04b754b70feb53b0bc71901a7c/lua/various-textobjs/charwise-textobjs.lua#L429

**Comment by chrisgrieser** [comment]
fixed all cases

**Comment by tuurep** [comment]
Astonishing. Thank you very much :smile:
